version: 2

sources:
  - name: raw_airbnb_data          
    database: AIRBNB              
    schema: RAW                    
    tables:
      - name: hosts
      - name: listings
      - name: reviews
